management:
  endpoints:
    enabled-by-default: true
    health:
      show-details: always
    web:
      exposure:
        include: '*'

server:
  port: 8888
spring:
  application:
    name: config-service